SELECT  
	MEMB.MEMBER_NAME AS "Nombre",
	MEMB.MEMBER_TOWN AS "Ciudad",
	MEMB.MEMBER_PHONE AS "Telefono",
	AW_MOVIES.MOVIE_NAME
FROM
PUBLIC.MEMBERS_MOVIE_RENTAL AS Mrent
JOIN (
	SELECT
		AW.AWARD_NOMINATION,
		AW.AWARD_WIN,
		M.MOVIE_ID,
		M.MOVIE_NAME  
	FROM PUBLIC.MOVIES AS M
	JOIN PUBLIC.AWARDS  AS AW
	ON M.MOVIE_ID = AW.MOVIE_ID 
	WHERE AW.AWARD_NOMINATION > 150 AND AW.AWARD_WIN < 50
) AS AW_MOVIES
ON MRENT.MOVIE_ID = AW_MOVIES.MOVIE_ID
JOIN PUBLIC.MEMBERS AS memb
ON MRENT.MEMBER_ID = MEMB.MEMBER_ID;

