//Lista nombre, nacionalidad y director de todas las películas

SELECT m.MOVIE_NAME, n.NATIONALITY_NAME, d.DIRECTOR_NAME  FROM PUBLIC.MOVIES AS m
INNER JOIN PUBLIC.DIRECTORS D
ON m.DIRECTOR_ID  = d.DIRECTOR_ID
INNER JOIN PUBLIC.NATIONALITIES AS N
ON m.NATIONALITY_ID  = N.NATIONALITY_ID 
ORDER BY m.MOVIE_NAME asc
