//Devuelve una lista de las últimas 10 películas que se han alquilado

SELECT M.MOVIE_NAME, MOVIERENT.MEMBER_RENTAL_DATE  FROM MOVIES AS M
INNER JOIN MEMBERS_MOVIE_RENTAL AS MOVIERENT
ON M.MOVIE_ID = MOVIERENT.MOVIE_ID 
ORDER BY MOVIERENT.MEMBER_RENTAL_DATE DESC LIMIT 10

