//Devuelve todas las películas creadas por directores nacidos a partir de 1980 y que todavía están vivos

SELECT M.MOVIE_NAME, D.DIRECTOR_NAME, D.DIRECTOR_BIRTH_DATE  FROM MOVIES AS M
INNER JOIN DIRECTORS AS D
ON M.DIRECTOR_ID = D.DIRECTOR_ID 
WHERE D.DIRECTOR_BIRTH_DATE >= '1980-01-01'
AND D.DIRECTOR_DEAD_DATE IS NULL
ORDER BY D.DIRECTOR_BIRTH_DATE ASC