SELECT 
	st.studio_name,
	N.NATIONALITY_NAME,
	COUNT(M.NATIONALITY_ID) Peliculas
FROM PUBLIC.MOVIES AS M
JOIN PUBLIC.STUDIOS AS st
ON m.STUDIO_ID = st.STUDIO_ID
JOIN PUBLIC.NATIONALITIES AS N
ON N.NATIONALITY_ID = M.NATIONALITY_ID 
GROUP BY M.NATIONALITY_ID,st.studio_name, N.NATIONALITY_NAME
ORDER BY Peliculas DESC , st.STUDIO_NAME DESC


