SELECT 	
	COUNT(A.ACTOR_ID) AS actores, 
	COUNT(D.DIRECTOR_ID) AS directores, 
	S.STUDIO_NAME  	
FROM PUBLIC.MOVIES AS M
JOIN (
	SELECT
		A.actor_name,
		A.ACTOR_ID, 
		MA.MOVIE_ID 
	FROM PUBLIC.ACTORS AS A
	JOIN PUBLIC.MOVIES_ACTORS  AS MA
	ON A.ACTOR_ID  = MA.ACTOR_ID 
	
)  A
ON A.MOVIE_ID = M.MOVIE_ID 
JOIN PUBLIC.STUDIOS AS S
ON M.STUDIO_ID = S.STUDIO_ID 
JOIN PUBLIC.DIRECTORS AS D
ON D.DIRECTOR_ID = M.MOVIE_ID
WHERE S.STUDIO_ACTIVE = 0
GROUP BY S.STUDIO_NAME;
